export const LOADING = 'LOADING'
export const SEARCH_ERROR = 'SEARCH_ERROR'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SET_TOKEN = 'SET_TOKEN'
export const EXPIRED_TOKEN = 'EXPIRED_TOKEN'
